name: Prueba Testing
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Comprobar respositorio
      uses: actions/checkout@v2
    - name: Configurar NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Ejecutar test
      run: npm test
